services:
  mongodb-server:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092" # Internal Docker network port
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

 # TODO: check client with certs, and gateway connection, vite config overrides      
  client:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./frontend/.env

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "4000:4000"
    env_file:
      - ./gateway/.env
    environment:
      - PERMISSION_SERVICE_URL=http://permission-service:3001
      - COURSES_SERVICE_URL=http://courses-service:3002
      - VIDEO_INITIALIZER_URL=http://video-initializer:3005
      - CLIENTURL=https://localhost
      - VITE_CLOUDFRONT_DOMAIN_URL=https://d1bxigp1z5p4f8.cloudfront.net

  s3-dal:
    build:
      context: ./s3-dal
      dockerfile: Dockerfile
    container_name: s3-dal
    ports:
      - "3004:3004"
    env_file:
      - ./s3-dal/.env

  permission-service:
    build:
      context: ./permission-service
      dockerfile: Dockerfile
    container_name: permission-service
    ports:
      - "3001:3001"
    env_file:
      - ./permission-service/.env
    environment:
      - MONGODB_URI=mongodb://mongodb-server:27017/segmentor
    depends_on:
      - mongodb-server

  video-analyzer:
    build:
      context: ./video-analyzer
      dockerfile: Dockerfile
    container_name: video-analyzer
    ports:
      - "3000:3000"
    env_file:
      - ./video-analyzer/.env
    environment:
      - KAFKA_URL=kafka:9092
      - S3_DAL_URL=http://s3-dal:3004
      - COURSES_SERVICE_URL=http://courses-service:3002
    depends_on:
      - kafka

  video-initializer:
    build:
      context: ./video-initializer
      dockerfile: Dockerfile
    container_name: video-initializer
    ports:
      - "3005:3005"
    env_file:
      - ./video-initializer/.env
    environment:
      - KAFKA_URL=kafka:9092
      - COURSES_SERVICE_URL=http://courses-service:3002
      - S3_DAL_URL=http://s3-dal:3004
    depends_on:
      - kafka

  transcript-service:
    build:
      context: ./transcript-service
      dockerfile: Dockerfile
    container_name: transcript-service
    ports:
      - "3006:3006"
    env_file:
      - ./transcript-service/.env
    environment:
      - S3_DAL_URL=http://s3-dal:3004

  courses-service:
    build:
      context: ./courses-service
      dockerfile: Dockerfile
    container_name: courses-service
    ports:
      - "3002:3002"
    env_file:
      - ./courses-service/.env
    environment:
      - MONGODB_URI=mongodb://mongodb-server:27017/segmentor
    depends_on:
      - mongodb-server
