services:
  client:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports: 
      - "8000:8000"
    env_file:
      - ./frontend/.env

  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "4000:4000"
    env_file:
      - ./gateway/.env
    environment:
      - PERMISSION_SERVICE_URL=http://permission-service:3001
      - COURSES_SERVICE_URL=http://courses-service:3002
      - VIDEO_INITIALIZER_SERVICE_URL=http://video-initializer:3005
      - CLIENTURL=http://localhost:8000

  s3-dal:
    build:
      context: ./s3-dal
      dockerfile: Dockerfile
    container_name: s3-dal
    ports:
      - "3004:3004"
    env_file:
      - ./s3-dal/.env

  permission-service:
    build:
      context: ./permission-service
      dockerfile: Dockerfile
    container_name: permission-service
    ports:
      - "3001:3001"
    env_file:
      - ./permission-service/.env
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/segmentor

  video-analyzer:
    build:
      context: ./video-analyzer
      dockerfile: Dockerfile
    container_name: video-analyzer
    ports:
      - "3000:3000"
    env_file:
      - ./video-analyzer/.env
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/segmentor
      - KAFKA_URL=host.docker.internal:9092
      - S3_DAL_URL=http://s3-dal:3004

  video-initializer:
    build:
      context: ./video-initializer
      dockerfile: Dockerfile
    container_name: video-initializer
    ports:
      - "3005:3005"
    env_file:
      - ./video-initializer/.env
    environment:
      - KAFKA_URL=host.docker.internal:9092

  transcript-service:
    build:
      context: ./transcript-service
      dockerfile: Dockerfile
    container_name: transcript-service
    ports:
      - "3006:3006"
    env_file:
      - ./transcript-service/.env
    environment:
      - S3_DAL_URL=http://s3-dal:3004

  courses-service:
    build:
      context: ./courses-service
      dockerfile: Dockerfile
    container_name: courses-service
    ports:
      - "3002:3002"
    env_file:
      - ./courses-service/.env
    environment:
      - MONGODB_URI=mongodb://host.docker.internal:27017/segmentor
